spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dokyung?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rlaehrud9919@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true

  jwt:
    key: asdjjfkljasljasdf
    live:
      accessToken: 3600000000

  cloud:
    aws:
      credentials:
        accessKey: AKIAXVDNQVOSA7LJTHPN
        secretKey: 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
      s3:
        bucket: onepiecee
      region:
        static: ap-northeast-2
      stack:
        auto: false