spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onepiece?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rlaehrud9919@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true


  jwt:
    key: asdfasdjflkasdasdfasfhdfgsd
    live:
      accessToken: 360000000000