name: Java CI with Gradle

on:
  push:
    branches:
      -main
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        java-version: [ 17 ]

    steps:
      - uses: actions/checkout@v2
          - uses: codecov/codecov-action@v1
          with:
          token : $ {{ secrets.CODECOV_TOKEN }}

      - name : Set up JDK 20
        uses : actions/setup-java@v2
        with:
          java-version : ${{ matrix.java_version }}
          distribution : 'adopt'

      - name: Setup Gradle
        run: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
